// <!-- scope: human-approved sub-task `heal-brief-too-long-for-context-window` of `promote-remaining-heal-recipes` decomposition. Final sub-task — closes the M1.13 ≥10-automated-heals bar. -->
//
// Helper: heal-brief-too-long-for-context-window
//
// Catalogued failure mode: a brief generated by `scripts/build_brief.py`
// exceeds the model's `max_tokens` (e.g., 200k for Sonnet, 128k for
// some local models). The spawn fails immediately with messages like:
//   - "context window exceeded"
//   - "input too long"
//   - "prompt_tokens (X) > model_max_input_tokens (Y)"
//   - "maximum context length is N tokens"
//
// Heal: detect via stderr regex → invoke the injected `rebuildFn`
// (which production binds to `scripts/build_brief.py --max-tokens=N`
// once that flag ships per the `build-brief-supports-max-tokens`
// follow-up task) → verify the regenerated brief size ≤ limit.
//
// Pivot path (see task body): the `build_brief.py --max-tokens` flag
// is a separate task; until it ships, the production binding for
// `rebuildFn` should refuse + leave the recipe as `operator-recipe`.
// The helper itself is still shippable — the seam is defined and the
// detection works.
//
// User-story: 007-agent-self-heals-catalogued-failures.md

import type { ApplyResult, DetectResult, VerifyResult } from "./types.js";

/** Injected I/O seams so tests run hermetically. */
export type BriefTooLongSeams = {
  /** Stderr buffer to scan for the context-window-exceeded signal. */
  stderr: string;
  /**
   * Path to the brief file the worker tried to use. The rebuild step
   * overwrites it with a shorter version.
   */
  briefFilePath: string;
  /**
   * Production binding: `python scripts/build_brief.py --max-tokens=N`
   * piped to `briefFilePath`. Tests stub with a no-op that records
   * the requested cap.
   * Throws on failure (rule #6 — let-it-crash at the I/O boundary).
   */
  rebuildFn: (maxTokens: number, briefFilePath: string) => void;
  /**
   * Reads the regenerated brief's byte count. Tests inject; production
   * binds to `statSync(briefFilePath).size`.
   */
  briefByteCountFn: () => number;
  /**
   * Target max tokens. Default: 100_000 (safe for Sonnet's 200k and
   * most local models' 128k). Caller can override per-model.
   */
  maxTokens?: number;
};

/** Default max-tokens — safe for Sonnet 200k and most local models 128k. */
export const DEFAULT_MAX_TOKENS = 100_000;

/**
 * Rough byte-to-token heuristic: ~4 bytes per token for English text
 * (per OpenAI tokenizer docs). Used for the verify step's size check.
 */
export const BYTES_PER_TOKEN_HEURISTIC = 4;

/**
 * Regex matching the context-window-exceeded signals. Cases:
 *
 *   - claude: "input too long" / "context window exceeded"
 *   - openai: "maximum context length is N tokens"
 *   - litellm: "prompt_tokens (X) > model_max_input_tokens (Y)"
 *   - generic: "context length exceeded", "context_length_exceeded"
 *
 * @type {RegExp}
 */
export const BRIEF_TOO_LONG_RE =
  /(context\s+(?:window|length)\s+(?:exceeded|too\s+long)|input\s+too\s+long|context_length_exceeded|prompt_tokens\s*\(\d+\)\s*>\s*model_max_input_tokens|maximum\s+context\s+length\s+is\s+\d+)/i;

/**
 * @otel-exempt pure-with-I/O-at-edge — OTEL span owned by caller.
 */
export function detect(seams: BriefTooLongSeams): DetectResult {
  if (!BRIEF_TOO_LONG_RE.test(seams.stderr)) {
    return { present: false };
  }
  return {
    present: true,
    signal: "brief-too-long-for-context-window",
    evidence: {
      briefFilePath: seams.briefFilePath,
      maxTokens: seams.maxTokens ?? DEFAULT_MAX_TOKENS,
      stderrPreview: seams.stderr.slice(0, 200),
    },
  };
}

/**
 * Invoke the rebuildFn with the target max-tokens cap. The production
 * binding runs `build_brief.py --max-tokens=N` and overwrites the
 * brief file.
 *
 * @otel-exempt pure-with-I/O-at-edge — rebuildFn is injected at the
 * seam; caller wraps in an OTEL heal span.
 */
export function apply(seams: BriefTooLongSeams): ApplyResult {
  const detection = detect(seams);
  if (!detection.present) {
    return {
      applied: false,
      changedFiles: [],
      notes: "no-op: stderr has no context-window-exceeded signal",
    };
  }
  const maxTokens = seams.maxTokens ?? DEFAULT_MAX_TOKENS;
  seams.rebuildFn(maxTokens, seams.briefFilePath);
  return {
    applied: true,
    changedFiles: [seams.briefFilePath],
    notes: `regenerated brief with max-tokens=${maxTokens}; caller should retry the spawn`,
  };
}

/**
 * Verify: read the regenerated brief's byte count and check it's
 * within the byte-budget heuristic (maxTokens × ~4 bytes/token).
 *
 * @otel-exempt pure-with-I/O-at-edge — briefByteCountFn is injected.
 */
export function verify(seams: BriefTooLongSeams): VerifyResult {
  const maxTokens = seams.maxTokens ?? DEFAULT_MAX_TOKENS;
  const byteBudget = maxTokens * BYTES_PER_TOKEN_HEURISTIC;
  const actualBytes = seams.briefByteCountFn();
  if (actualBytes <= byteBudget) {
    return { healed: true };
  }
  return { healed: false, residualSignal: "brief-too-long-for-context-window" };
}
