#!/usr/bin/env bash
# Minsky bootstrap script.
#
# Usage:
#   ./setup.sh             — install / repair (idempotent; safe to re-run)
#   ./setup.sh --doctor    — self-tests only; no mutations
#   ./setup.sh --reset     — remove .minsky/ and re-install from scratch
#   ./setup.sh --help      — print this header
#
# Anti-patterns refused (per constitutional rule #6 stay-alive + rule #7 chaos):
#   - no `sudo`
#   - no `rm -rf` outside `.minsky/`
#   - no shell-rc mutation (.zshrc / .bashrc / etc.)
#   - no unpinned `curl … | bash` piping
#
# Failure modes & chaos verification (per vision.md § 7):
#   | Failure mode                     | Fault axis     | Expected behavior            | Chaos test                                          |
#   |----------------------------------|----------------|------------------------------|-----------------------------------------------------|
#   | Concurrent setup.sh invocation   | concurrency    | loud-crash with EX_TEMPFAIL  | run two `./setup.sh` simultaneously; second exits 75|
#   | .minsky/state.json corrupted     | upstream-bad   | loud-crash; suggest --reset  | echo "garbage" > .minsky/state.json; re-run         |
#   | Missing critical prereq (node)   | dependency     | loud-crash with exit 1       | PATH=/usr/bin ./setup.sh; exits non-zero            |
#   | Missing optional prereq (claude) | dependency     | graceful-degrade with warn   | ./setup.sh on host without claude CLI               |
#   | Mid-run interrupt (SIGINT)       | process-signal | EXIT trap prints state path  | start ./setup.sh; Ctrl-C; observe trap output       |
#   | jq absent                        | dependency     | graceful-degrade; ledger off | uninstall jq; ./setup.sh; observe ledger skip warn  |
#
# State persistence (.minsky/state.json):
#   {
#     "schema_version": "1",
#     "defaults": {
#       "budget_tier": "Max5",
#       "observability": "sqlite",
#       "topology": "single-machine"
#     },
#     "ntfy": { "topic": "<auto-generated random topic, lowercase a-z0-9>" },
#     "adapters": {},
#     "ledger": { "<step-name>": { "completed_at": "<ISO-8601 UTC>", "exit_code": 0 } },
#     "last_self_test": {}
#   }
# A reference template lives at distribution/state.example.json.
#
# selfTest() adapter contract (consumed by --doctor; defined in TS at
# novel/adapters/types/src/index.ts):
#   { status: "green" | "yellow" | "red", message: string, latencyMs: number, lastCheck: string }
#   Aggregation: red dominates yellow dominates green. (See aggregateStatus.)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

STATE_DIR="$ROOT/.minsky"
STATE_FILE="$STATE_DIR/state.json"
# POSIX-portable lock: a directory whose `mkdir` is the atomic claim.
# Linux's flock and macOS's lockf are not both available, so we use
# the cross-platform mkdir-based idiom with stale-PID cleanup.
LOCK_DIR="$STATE_DIR/setup.lock.d"
LOG_FILE="$STATE_DIR/setup.log"
# Reference schema template (not consumed by this script; documented for users):
#   "$ROOT/distribution/state.example.json"

# --- mode parsing ---
MODE="install"
for arg in "$@"; do
  case "$arg" in
    --doctor) MODE="doctor" ;;
    --reset)  MODE="reset" ;;
    -h|--help)
      # Print the leading documentation block of this script.
      sed -n '2,/^set -euo/p' "$0" | sed -e 's/^# \?//' -e '$d'
      exit 0
      ;;
    *)
      printf 'Unknown argument: %s\n' "$arg" >&2
      printf 'Run with --help for usage.\n' >&2
      exit 64  # EX_USAGE
      ;;
  esac
done

# --- color / no-color / CI awareness ---
if [ -t 1 ] && [ -z "${NO_COLOR:-}" ] && [ -z "${CI:-}" ]; then
  C_BOLD=$'\033[1m'; C_DIM=$'\033[2m'
  C_RED=$'\033[31m'; C_YELLOW=$'\033[33m'; C_GREEN=$'\033[32m'; C_RESET=$'\033[0m'
else
  C_BOLD=""; C_DIM=""
  C_RED=""; C_YELLOW=""; C_GREEN=""; C_RESET=""
fi
bold() { printf '%s%s%s\n' "$C_BOLD" "$*" "$C_RESET"; }
dim()  { printf '%s%s%s\n' "$C_DIM"  "$*" "$C_RESET"; }
ok()   { printf '%s✓%s %s\n' "$C_GREEN"  "$C_RESET" "$*"; }
warn() { printf '%s⚠%s %s\n' "$C_YELLOW" "$C_RESET" "$*"; }
err()  { printf '%s✗%s %s\n' "$C_RED"    "$C_RESET" "$*" >&2; }

CURRENT_STEP="init"
SETUP_FAILED=0

# --- trap on EXIT ---
on_exit() {
  local exit_code=$?
  if [ "$exit_code" -ne 0 ] && [ "$SETUP_FAILED" -eq 0 ]; then
    err "Setup failed at step: ${CURRENT_STEP}"
    err "  state path : $STATE_FILE"
    err "  log path   : $LOG_FILE"
    err "  next step  : re-run ./setup.sh (idempotent) or ./setup.sh --reset to start fresh"
  fi
  # Release the lock if we hold it (release_lock is defined after this trap is set).
  if declare -F release_lock >/dev/null 2>&1; then
    release_lock
  fi
  exit "$exit_code"
}
trap on_exit EXIT

# --- mode: --reset ---
# Explicit safety: only ever rm "$STATE_DIR" — never anything else, never with a glob,
# never outside the repo root. Per anti-patterns above.
if [ "$MODE" = "reset" ]; then
  bold "Minsky reset"
  if [ -d "$STATE_DIR" ]; then
    rm -rf -- "$STATE_DIR"
    ok ".minsky/ removed"
  else
    dim ".minsky/ not present — nothing to remove"
  fi
  echo
  MODE="install"  # fall through to a fresh install
fi

# --- ensure state dir + acquire lock (POSIX-portable mkdir-based) ---
mkdir -p "$STATE_DIR"

acquire_lock() {
  if mkdir "$LOCK_DIR" 2>/dev/null; then
    echo "$$" > "$LOCK_DIR/pid"
    return 0
  fi
  # mkdir failed: lock is held. Check if holder is still alive.
  if [ -f "$LOCK_DIR/pid" ]; then
    local holder
    holder=$(cat "$LOCK_DIR/pid" 2>/dev/null || echo "")
    if [ -n "$holder" ] && kill -0 "$holder" 2>/dev/null; then
      err "Another setup.sh run is in progress (lock: $LOCK_DIR, pid: $holder)"
      err "If no other run is active, the lock is stale. Remove it: rm -rf $LOCK_DIR"
      SETUP_FAILED=1
      exit 75  # EX_TEMPFAIL
    fi
    # holder is dead → stale lock, reclaim
    rm -rf "$LOCK_DIR"
    mkdir "$LOCK_DIR"
    echo "$$" > "$LOCK_DIR/pid"
  else
    # lock dir exists but pid file doesn't — corrupt; reclaim
    rm -rf "$LOCK_DIR"
    mkdir "$LOCK_DIR"
    echo "$$" > "$LOCK_DIR/pid"
  fi
}
acquire_lock

# Release the lock on exit (added before main work; trap chains via on_exit).
release_lock() {
  rm -rf "$LOCK_DIR"
}

# --- have_jq detection (used by ledger; missing jq → graceful-degrade, ledger skipped) ---
have_jq=0
if command -v jq >/dev/null 2>&1; then
  have_jq=1
fi

# --- state.json initialisation (only on first run; idempotent) ---
if [ ! -f "$STATE_FILE" ]; then
  CURRENT_STEP="init-state"
  # 16-hex-char topic suffix; `od -An -N8 -tx1` reads exactly 8 bytes and exits
  # cleanly (no SIGPIPE under `set -o pipefail`).
  TOPIC="minsky-$(od -An -N8 -tx1 < /dev/urandom | tr -d ' \n')"
  cat > "$STATE_FILE" <<EOF
{
  "schema_version": "1",
  "defaults": {
    "budget_tier": "Max5",
    "observability": "sqlite",
    "topology": "single-machine"
  },
  "ntfy": { "topic": "$TOPIC" },
  "adapters": {},
  "ledger": {},
  "last_self_test": {}
}
EOF
  ok "state initialised at $STATE_FILE (ntfy topic: $TOPIC)"
else
  # validate the existing state can be parsed
  if [ "$have_jq" -eq 1 ] && ! jq -e . "$STATE_FILE" >/dev/null 2>&1; then
    CURRENT_STEP="validate-state"
    err "$STATE_FILE is not valid JSON"
    err "run ./setup.sh --reset to rebuild from scratch (this is the only path that touches your local state)"
    SETUP_FAILED=1
    exit 1
  fi
fi

# --- ledger helpers: cache step completion in state.json ---
ledger_done() {
  local step="$1"
  if [ "$have_jq" -eq 1 ]; then
    local now tmp
    now=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    tmp=$(mktemp)
    jq --arg s "$step" --arg t "$now" \
       '.ledger[$s] = { completed_at: $t, exit_code: 0 }' \
       "$STATE_FILE" > "$tmp"
    mv "$tmp" "$STATE_FILE"
  fi
}
ledger_has() {
  local step="$1"
  if [ "$have_jq" -eq 1 ]; then
    jq -e --arg s "$step" '.ledger[$s] != null' "$STATE_FILE" >/dev/null 2>&1
  else
    return 1
  fi
}

# --- mode: --doctor (self-tests only, no mutations) ---
if [ "$MODE" = "doctor" ]; then
  bold "Minsky doctor — self-tests only"
  echo

  STATUS="green"

  # built-in checks (prerequisites)
  if command -v git    >/dev/null 2>&1; then ok "git";    else warn "git missing";    STATUS="red";    fi
  if command -v node   >/dev/null 2>&1; then ok "node";   else warn "node missing";   STATUS="red";    fi
  if command -v npx    >/dev/null 2>&1; then ok "npx";    else warn "npx missing";    STATUS="red";    fi
  if command -v claude >/dev/null 2>&1; then ok "claude"; else warn "claude CLI missing"; STATUS="${STATUS/green/yellow}"; fi
  if command -v jq     >/dev/null 2>&1; then ok "jq";     else warn "jq missing — ledger writes are skipped"; STATUS="${STATUS/green/yellow}"; fi

  # adapter selfTest aggregation: today there are no wired adapters; future P1 PRs add them.
  # The contract is documented at novel/adapters/types/src/index.ts.
  echo
  dim "  adapters wired into doctor: 0 (each P1+ adapter PR registers its selfTest here)"
  echo

  case "$STATUS" in
    green)  ok    "GREEN  — all checks passed" ;;
    yellow) warn  "YELLOW — non-critical prerequisites missing (see above)" ;;
    red)
      err "RED    — critical prerequisite missing"
      SETUP_FAILED=1
      exit 1
      ;;
  esac
  exit 0
fi

# --- mode: install (default; reached after --reset too) ---
bold "Minsky setup"
echo

# step: prereqs
CURRENT_STEP="prereqs"
if ! ledger_has "$CURRENT_STEP"; then
  bold "Checking prerequisites…"
  command -v git  >/dev/null 2>&1 || { err "git not found";  SETUP_FAILED=1; exit 1; }
  command -v node >/dev/null 2>&1 || { err "node not found"; SETUP_FAILED=1; exit 1; }
  command -v npx  >/dev/null 2>&1 || { err "npx not found";  SETUP_FAILED=1; exit 1; }
  command -v claude >/dev/null 2>&1 \
    || warn "claude CLI not found — install: https://docs.claude.com/en/docs/claude-code/overview"
  command -v jq >/dev/null 2>&1 \
    || warn "jq not found — install for setup ledger to work (brew install jq / apt install jq)"
  ok "prerequisites OK"
  ledger_done "$CURRENT_STEP"
else
  ok "prerequisites (cached)"
fi
echo

# step: git
CURRENT_STEP="git-init"
if ! ledger_has "$CURRENT_STEP"; then
  if [ ! -d .git ]; then
    git init -q
    ok "git initialised"
  else
    ok "git already initialised"
  fi
  ledger_done "$CURRENT_STEP"
else
  ok "git (cached)"
fi
echo

# step: tasks-md tooling — install global binaries pinned to ^0.7.0
# NOTE: `tasks install` (the CLI's auto-install of /next-task) is broken in 0.7.0
# (regression tracked at tasksmd/tasks.md PR #77). Skipped here; the SKILL.md
# files at .claude/skills/{next-task,lint-tasks}/ are committed in the repo.
CURRENT_STEP="tasks-md-tooling"
if ! ledger_has "$CURRENT_STEP"; then
  bold "Installing tasks.md tooling (pinned ^0.7.0)…"
  if command -v tasks >/dev/null 2>&1 \
       && command -v tasks-mcp >/dev/null 2>&1 \
       && command -v tasks-lint >/dev/null 2>&1; then
    ok "tasks / tasks-lint / tasks-mcp already on PATH"
  else
    if npm i -g '@tasks-md/cli@^0.7.0' '@tasks-md/lint@^0.7.0' 'tasks-mcp@^0.7.0' 2>>"$LOG_FILE"; then
      ok "tasks-md tooling installed"
    else
      warn "tasks-md tooling install failed; see $LOG_FILE — try manually: npm i -g @tasks-md/cli@^0.7.0 @tasks-md/lint@^0.7.0 tasks-mcp@^0.7.0"
    fi
  fi
  ledger_done "$CURRENT_STEP"
else
  ok "tasks-md tooling (cached)"
fi
echo

# --- final report ---
echo
bold "Summary"
TOPIC="<unset>"
if [ "$have_jq" -eq 1 ]; then
  TOPIC=$(jq -r '.ntfy.topic // "<unset>"' "$STATE_FILE" 2>/dev/null || echo "<unset>")
fi
dim "  ntfy topic       : $TOPIC"
dim "  state file       : $STATE_FILE"
dim "  log file         : $LOG_FILE  (created lazily on tooling-install failures)"
dim "  re-run anytime   : ./setup.sh"
dim "  rebuild from zero: ./setup.sh --reset"
dim "  self-tests only  : ./setup.sh --doctor"
echo
ok "GREEN — minsky setup complete (v0)"
echo
dim "Future P1+ adapter PRs (observability-adapter-v0, supervisor-setup, budget-guard-v0, etc.)"
dim "wire their selfTest() into the --doctor aggregation per the contract documented at"
dim "novel/adapters/types/src/index.ts. Until then, --doctor only checks prerequisites."

# Next-step suggestions (printed after the GREEN banner so the user sees them last).
echo
bold "Next steps inside Claude Code from this directory:"
cat <<'EOF'

  1. /plugin marketplace add https://github.com/Yeachan-Heo/oh-my-claudecode
     /plugin install oh-my-claudecode
     /omc-setup

  2. /plugin install ralph-wiggum

  3. /next-task   (picks the highest-priority unblocked task from TASKS.md)

EOF
