#!/usr/bin/env bash
# Minsky bootstrap script.
#
# Usage:
#   ./setup.sh             — install / repair (idempotent; safe to re-run)
#   ./setup.sh --doctor    — self-tests only; no mutations
#   ./setup.sh --reset     — remove .minsky/ and re-install from scratch
#   ./setup.sh --dogfood   — start the supervisor on this repo (Minsky-on-itself)
#   ./setup.sh --help      — print this header
#
# Anti-patterns refused (per constitutional rule #6 stay-alive + rule #7 chaos):
#   - no `sudo`
#   - no `rm -rf` outside `.minsky/`
#   - no shell-rc mutation (.zshrc / .bashrc / etc.)
#   - no unpinned `curl … | bash` piping
#
# Failure modes & chaos verification (per vision.md § 7):
#   | Failure mode                     | Fault axis     | Expected behavior            | Chaos test                                          |
#   |----------------------------------|----------------|------------------------------|-----------------------------------------------------|
#   | Concurrent setup.sh invocation   | concurrency    | loud-crash with EX_TEMPFAIL  | run two `./setup.sh` simultaneously; second exits 75|
#   | .minsky/state.json corrupted     | upstream-bad   | loud-crash; suggest --reset  | echo "garbage" > .minsky/state.json; re-run         |
#   | Missing critical prereq (node)   | dependency     | loud-crash with exit 1       | PATH=/usr/bin ./setup.sh; exits non-zero            |
#   | Missing optional prereq (claude) | dependency     | graceful-degrade with warn   | ./setup.sh on host without claude CLI               |
#   | Mid-run interrupt (SIGINT)       | process-signal | EXIT trap prints state path  | start ./setup.sh; Ctrl-C; observe trap output       |
#   | jq absent                        | dependency     | graceful-degrade; ledger off | uninstall jq; ./setup.sh; observe ledger skip warn  |
#
# State persistence (.minsky/state.json):
#   {
#     "schema_version": "1",
#     "defaults": {
#       "budget_tier": "Max5",
#       "observability": "sqlite",
#       "topology": "single-machine"
#     },
#     "ntfy": { "topic": "<auto-generated random topic, lowercase a-z0-9>" },
#     "adapters": {},
#     "ledger": { "<step-name>": { "completed_at": "<ISO-8601 UTC>", "exit_code": 0 } },
#     "last_self_test": {}
#   }
# A reference template lives at distribution/state.example.json.
#
# selfTest() adapter contract (consumed by --doctor; defined in TS at
# novel/adapters/types/src/index.ts):
#   { status: "green" | "yellow" | "red", message: string, latencyMs: number, lastCheck: string }
#   Aggregation: red dominates yellow dominates green. (See aggregateStatus.)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

# Slice 1 of `minsky-fresh-clone-health-checks` — single source of truth
# for the minimum Node major version. Mirrors `package.json`'s
# `engines.node` field (`>=20.0.0`). Bump in lockstep when the field
# changes; the test layer checks both stay in sync.
MINSKY_NODE_MIN_MAJOR=20

STATE_DIR="$ROOT/.minsky"
STATE_FILE="$STATE_DIR/state.json"
# POSIX-portable lock: a directory whose `mkdir` is the atomic claim.
# Linux's flock and macOS's lockf are not both available, so we use
# the cross-platform mkdir-based idiom with stale-PID cleanup.
LOCK_DIR="$STATE_DIR/setup.lock.d"
LOG_FILE="$STATE_DIR/setup.log"
# Reference schema template (not consumed by this script; documented for users):
#   "$ROOT/distribution/state.example.json"

# --- mode parsing ---
MODE="install"
for arg in "$@"; do
  case "$arg" in
    --doctor)  MODE="doctor" ;;
    --reset)   MODE="reset" ;;
    --dogfood) MODE="dogfood" ;;
    -h|--help)
      # Print the leading documentation block of this script.
      sed -n '2,/^set -euo/p' "$0" | sed -e 's/^# \?//' -e '$d'
      exit 0
      ;;
    *)
      printf 'Unknown argument: %s\n' "$arg" >&2
      printf 'Run with --help for usage.\n' >&2
      exit 64  # EX_USAGE
      ;;
  esac
done

# --- color / no-color / CI awareness ---
if [ -t 1 ] && [ -z "${NO_COLOR:-}" ] && [ -z "${CI:-}" ]; then
  C_BOLD=$'\033[1m'; C_DIM=$'\033[2m'
  C_RED=$'\033[31m'; C_YELLOW=$'\033[33m'; C_GREEN=$'\033[32m'; C_RESET=$'\033[0m'
else
  C_BOLD=""; C_DIM=""
  C_RED=""; C_YELLOW=""; C_GREEN=""; C_RESET=""
fi
bold() { printf '%s%s%s\n' "$C_BOLD" "$*" "$C_RESET"; }
dim()  { printf '%s%s%s\n' "$C_DIM"  "$*" "$C_RESET"; }
ok()   { printf '%s✓%s %s\n' "$C_GREEN"  "$C_RESET" "$*"; }
warn() { printf '%s⚠%s %s\n' "$C_YELLOW" "$C_RESET" "$*"; }
err()  { printf '%s✗%s %s\n' "$C_RED"    "$C_RESET" "$*" >&2; }

CURRENT_STEP="init"
SETUP_FAILED=0

# --- trap on EXIT ---
on_exit() {
  local exit_code=$?
  if [ "$exit_code" -ne 0 ] && [ "$SETUP_FAILED" -eq 0 ]; then
    err "Setup failed at step: ${CURRENT_STEP}"
    err "  state path : $STATE_FILE"
    err "  log path   : $LOG_FILE"
    err "  next step  : re-run ./setup.sh (idempotent) or ./setup.sh --reset to start fresh"
  fi
  # Release the lock if we hold it (release_lock is defined after this trap is set).
  if declare -F release_lock >/dev/null 2>&1; then
    release_lock
  fi
  exit "$exit_code"
}
trap on_exit EXIT

# --- mode: --reset ---
# Explicit safety: only ever rm "$STATE_DIR" — never anything else, never with a glob,
# never outside the repo root. Per anti-patterns above.
if [ "$MODE" = "reset" ]; then
  bold "Minsky reset"
  if [ -d "$STATE_DIR" ]; then
    rm -rf -- "$STATE_DIR"
    ok ".minsky/ removed"
  else
    dim ".minsky/ not present — nothing to remove"
  fi
  echo
  MODE="install"  # fall through to a fresh install
fi

# --- ensure state dir + acquire lock (POSIX-portable mkdir-based) ---
mkdir -p "$STATE_DIR"

acquire_lock() {
  if mkdir "$LOCK_DIR" 2>/dev/null; then
    echo "$$" > "$LOCK_DIR/pid"
    return 0
  fi
  # mkdir failed: lock is held. Check if holder is still alive.
  if [ -f "$LOCK_DIR/pid" ]; then
    local holder
    holder=$(cat "$LOCK_DIR/pid" 2>/dev/null || echo "")
    if [ -n "$holder" ] && kill -0 "$holder" 2>/dev/null; then
      err "Another setup.sh run is in progress (lock: $LOCK_DIR, pid: $holder)"
      err "If no other run is active, the lock is stale. Remove it: rm -rf $LOCK_DIR"
      SETUP_FAILED=1
      exit 75  # EX_TEMPFAIL
    fi
    # holder is dead → stale lock, reclaim
    rm -rf "$LOCK_DIR"
    mkdir "$LOCK_DIR"
    echo "$$" > "$LOCK_DIR/pid"
  else
    # lock dir exists but pid file doesn't — corrupt; reclaim
    rm -rf "$LOCK_DIR"
    mkdir "$LOCK_DIR"
    echo "$$" > "$LOCK_DIR/pid"
  fi
}
acquire_lock

# Release the lock on exit (added before main work; trap chains via on_exit).
release_lock() {
  rm -rf "$LOCK_DIR"
}

# --- have_jq detection (used by ledger; missing jq → graceful-degrade, ledger skipped) ---
have_jq=0
if command -v jq >/dev/null 2>&1; then
  have_jq=1
fi

# --- check_node_major: print the running node's major version (or empty on failure) ---
# Slice 1 of `minsky-fresh-clone-health-checks`. Portable across nvm /
# asdf / fnm / brew node — they all expose `node --version` returning
# `vMAJOR.MINOR.PATCH`. Returns empty on any failure (treated as
# "node not detectable" → RED in doctor, fatal in install).
check_node_major() {
  local v
  v=$(node --version 2>/dev/null) || return 1
  v=${v#v}             # strip leading "v"
  v=${v%%.*}           # take the first segment (major)
  case "$v" in
    *[!0-9]*|"") return 1 ;;
    *) printf '%s' "$v" ;;
  esac
}

# --- check_git_config_path: detect git config keys pointing at non-existent paths ---
# Slice 3 of `minsky-cross-machine-dotfile-checks`. Generalises PRs
# #394/#395 (lefthook permission-denial fix) to the broader set of
# dotfile-controlled git config keys (e.g., `core.hooksPath` synced
# across machines with different usernames → invalid path on this
# host). For each key in MINSKY_PATH_CONFIG_KEYS, if set and pointing
# at a path that doesn't exist, emits a YELLOW warn with the recovery
# command. Detect-only (per the operator's chosen aggressiveness —
# git config is outside `.minsky/`).
MINSKY_PATH_CONFIG_KEYS="core.hooksPath core.attributesfile core.excludesfile"

check_git_config_path() {
  local key="$1"
  local origin_value
  origin_value=$(git config --show-origin --get "$key" 2>/dev/null) || return 0  # unset → ok
  [ -z "$origin_value" ] && return 0
  local value origin_raw scope expanded
  value=$(printf '%s' "$origin_value" | awk -F'\t' '{print $2}')
  origin_raw=$(printf '%s' "$origin_value" | awk -F'\t' '{print $1}')
  [ -z "$value" ] && return 0
  # Tilde expansion: git config values often use `~/<path>` for $HOME-
  # relative paths (e.g. `core.excludesfile = ~/.gitignore_global`).
  # Quoted `[ -e "$value" ]` won't expand tilde — do it manually.
  case "$value" in
    "~/"*) expanded="${HOME:-}${value#\~}" ;;
    "~")   expanded="${HOME:-}" ;;
    *)     expanded="$value" ;;
  esac
  if [ -e "$expanded" ]; then
    return 0
  fi
  # Path is set but doesn't exist — broken.
  if printf '%s' "$origin_raw" | grep -q "/etc/git"; then
    scope="--system"
  elif [ -n "${HOME:-}" ] && printf '%s' "$origin_raw" | grep -q "$HOME"; then
    scope="--global"
  elif printf '%s' "$origin_raw" | grep -q "\.git/config"; then
    scope="--local"
  else
    scope=""
  fi
  warn "git config $key points at $value which does not exist; recover with \`git config $scope --unset $key\`"
  return 1
}

# --- state.json initialisation (only on first run; idempotent) ---
if [ ! -f "$STATE_FILE" ]; then
  CURRENT_STEP="init-state"
  # 16-hex-char topic suffix; `od -An -N8 -tx1` reads exactly 8 bytes and exits
  # cleanly (no SIGPIPE under `set -o pipefail`).
  TOPIC="minsky-$(od -An -N8 -tx1 < /dev/urandom | tr -d ' \n')"
  cat > "$STATE_FILE" <<EOF
{
  "schema_version": "1",
  "defaults": {
    "budget_tier": "Max5",
    "observability": "sqlite",
    "topology": "single-machine"
  },
  "ntfy": { "topic": "$TOPIC" },
  "adapters": {},
  "ledger": {},
  "last_self_test": {}
}
EOF
  ok "state initialised at $STATE_FILE (ntfy topic: $TOPIC)"
else
  # validate the existing state can be parsed
  if [ "$have_jq" -eq 1 ] && ! jq -e . "$STATE_FILE" >/dev/null 2>&1; then
    CURRENT_STEP="validate-state"
    err "$STATE_FILE is not valid JSON"
    err "run ./setup.sh --reset to rebuild from scratch (this is the only path that touches your local state)"
    SETUP_FAILED=1
    exit 1
  fi
fi

# --- ledger helpers: cache step completion in state.json ---
ledger_done() {
  local step="$1"
  if [ "$have_jq" -eq 1 ]; then
    local now tmp
    now=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    tmp=$(mktemp)
    jq --arg s "$step" --arg t "$now" \
       '.ledger[$s] = { completed_at: $t, exit_code: 0 }' \
       "$STATE_FILE" > "$tmp"
    mv "$tmp" "$STATE_FILE"
  fi
}
ledger_has() {
  local step="$1"
  if [ "$have_jq" -eq 1 ]; then
    jq -e --arg s "$step" '.ledger[$s] != null' "$STATE_FILE" >/dev/null 2>&1
  else
    return 1
  fi
}

# --- mode: --doctor (self-tests only, no mutations) ---
if [ "$MODE" = "doctor" ]; then
  bold "Minsky doctor — self-tests only"
  echo

  STATUS="green"

  # built-in checks (prerequisites)
  if command -v git    >/dev/null 2>&1; then ok "git";    else warn "git missing";    STATUS="red";    fi
  if command -v node   >/dev/null 2>&1; then ok "node";   else warn "node missing";   STATUS="red";    fi
  # Slice 1 of `minsky-fresh-clone-health-checks` — node MAJOR-version
  # gate. The engines field says `>=20.0.0`; on a host with Node 18
  # the install path silently passes prereqs but pnpm later emits an
  # opaque `ERR_PNPM_UNSUPPORTED_PLATFORM`. Catch up-front with a
  # clear "below the >=N requirement" message.
  if command -v node >/dev/null 2>&1; then
    NODE_MAJOR=$(check_node_major || true)
    if [ -z "$NODE_MAJOR" ]; then
      warn "node version unparsable — \`node --version\` returned non-standard output"
      STATUS="${STATUS/green/yellow}"
    elif [ "$NODE_MAJOR" -lt "$MINSKY_NODE_MIN_MAJOR" ]; then
      warn "node ${NODE_MAJOR}.x.x is below the >=${MINSKY_NODE_MIN_MAJOR} engine requirement (see package.json engines.node)"
      STATUS="red"
    else
      ok "node major ≥${MINSKY_NODE_MIN_MAJOR} (running ${NODE_MAJOR}.x.x)"
    fi
  fi
  if command -v npx    >/dev/null 2>&1; then ok "npx";    else warn "npx missing";    STATUS="red";    fi
  # Slice 1 of `minsky-fresh-clone-health-checks` — pnpm is the install
  # command. setup.sh / pnpm install / prepare hook / minsky doctor all
  # depend on it being on PATH. RED if missing.
  if command -v pnpm   >/dev/null 2>&1; then ok "pnpm";   else warn "pnpm missing — install via \`corepack enable\` (Node ≥16.13) OR \`brew install pnpm\` OR \`npm i -g pnpm\`"; STATUS="red"; fi
  if command -v claude >/dev/null 2>&1; then ok "claude"; else warn "claude CLI missing"; STATUS="${STATUS/green/yellow}"; fi
  if command -v jq     >/dev/null 2>&1; then ok "jq";     else warn "jq missing — ledger writes are skipped"; STATUS="${STATUS/green/yellow}"; fi
  # Push-channel deps: NtfyNotifier (novel/adapters/notifier) shells out to either
  # `curl` (the HTTP fallback that hits https://ntfy.sh/<topic>) or the `ntfy`
  # CLI. With state.json seeded with `ntfy.topic` on first install, a host that
  # has neither will silently drop budget-paused pushes (the daemon's exactly-
  # once notify hook lands a no-op). Surface that as YELLOW per
  # `setup-doctor-ntfy-check` so --doctor matches the actual fault axis (Beyer
  # SRE 2016 ch. 6 — health checks must cover the real failure surface).
  if command -v curl   >/dev/null 2>&1; then ok "curl";   else warn "curl missing — push notifications disabled"; STATUS="${STATUS/green/yellow}"; fi
  if command -v ntfy   >/dev/null 2>&1; then ok "ntfy";   else warn "ntfy CLI missing — pushes fall back to curl"; STATUS="${STATUS/green/yellow}"; fi

  # Slice 3 of `minsky-cross-machine-dotfile-checks` — git config
  # sanity. Detect-only; broken paths surface as YELLOW (don't block
  # daemon). Mirrors the corresponding section in `minsky doctor`.
  for k in $MINSKY_PATH_CONFIG_KEYS; do
    if check_git_config_path "$k"; then
      ok "git config $k"
    else
      STATUS="${STATUS/green/yellow}"
    fi
  done

  # adapter selfTest aggregation: today there are no wired adapters; future P1 PRs add them.
  # The contract is documented at novel/adapters/types/src/index.ts.
  echo
  dim "  adapters wired into doctor: 0 (each P1+ adapter PR registers its selfTest here)"
  echo

  case "$STATUS" in
    green)  ok    "GREEN  — all checks passed" ;;
    yellow) warn  "YELLOW — non-critical prerequisites missing (see above)" ;;
    red)
      err "RED    — critical prerequisite missing"
      SETUP_FAILED=1
      exit 1
      ;;
  esac
  exit 0
fi

# --- mode: --dogfood (start Minsky's supervisor on this repo) ---
#
# Implements user-stories/001-loop-runs-overnight.md (Minsky on itself —
# the dual-purpose framing's first surface per vision.md § "What Minsky
# is" + rule #12). Renders the supervisor unit-file templates from
# `distribution/{systemd,launchd}/` with `${MINSKY_HOME}` substituted
# to `$ROOT`, drops them into the operator's user-scope unit dir,
# loads them via `systemctl --user enable --now` (Linux) or
# `launchctl bootstrap gui/$(id -u)` (macOS), and verifies the
# supervisor reports active.
#
# Idempotent: re-invoking `--dogfood` on a host where the supervisor
# is already loaded re-renders the units (catches drift if templates
# change) and re-runs the load-confirm step. The operator's escape
# hatch is documented at the end of the run.
#
# Anchor: rule #12 (vision.md § "Scope discipline" — the Minsky-on-
# itself loop is the substrate the scope-discipline rule applies to);
# distribution/README.md (the multi-line install snippet this flag
# consolidates into one command); Armstrong, *Programming Erlang*,
# 2007 (supervision tree — `enable --now` mirrors OTP's "start the
# supervisor and let it boot the children").
if [ "$MODE" = "dogfood" ]; then
  bold "Minsky dogfood — start supervisor on this repo (Minsky on itself)"
  echo

  # Prereq: doctor must be at least YELLOW (red blocks dogfood — pushes
  # would silently drop, budget-guard couldn't read state, etc.).
  CURRENT_STEP="dogfood-doctor-precheck"
  if ! command -v envsubst >/dev/null 2>&1; then
    err "envsubst not found — install gettext (brew install gettext / apt install gettext-base)"
    SETUP_FAILED=1
    exit 1
  fi
  ok "envsubst on PATH"

  # OS detect → choose unit dir + load command.
  os="$(uname -s)"
  case "$os" in
    Darwin)
      unit_dir="$HOME/Library/LaunchAgents"
      template_dir="$ROOT/distribution/launchd"
      template_glob="*.plist"
      load_cmd_label="launchctl bootstrap gui/$(id -u)"
      ;;
    Linux)
      unit_dir="$HOME/.config/systemd/user"
      template_dir="$ROOT/distribution/systemd"
      # Includes *.timer so minsky-auto-merge.timer (and any future
      # periodic-task units) ship alongside services and targets.
      template_glob="*.service *.target *.timer"
      load_cmd_label="systemctl --user enable --now"
      ;;
    *)
      err "unsupported OS: $os (only Darwin / Linux carry supervisor unit-file templates)"
      SETUP_FAILED=1
      exit 1
      ;;
  esac
  ok "OS detected: $os → $template_dir → $unit_dir"

  if [ ! -d "$template_dir" ]; then
    err "$template_dir missing — distribution layout drift; re-clone or fix locally"
    SETUP_FAILED=1
    exit 1
  fi

  mkdir -p "$unit_dir"

  # Render templates with `${MINSKY_HOME}` → $ROOT. Idempotent overwrite.
  CURRENT_STEP="dogfood-render-units"
  rendered=0
  # Use $template_glob without quoting so the * expands in the templates.
  # shellcheck disable=SC2086
  for f in $template_dir/$template_glob; do
    [ -f "$f" ] || continue
    target="$unit_dir/$(basename "$f")"
    MINSKY_HOME="$ROOT" envsubst '${MINSKY_HOME}' < "$f" > "$target"
    rendered=$((rendered + 1))
  done
  ok "rendered $rendered unit-file template(s) into $unit_dir"

  # Load + confirm.
  CURRENT_STEP="dogfood-load-supervisor"
  case "$os" in
    Darwin)
      for f in "$unit_dir"/com.minsky.*.plist; do
        [ -f "$f" ] || continue
        # `bootstrap` errors if already loaded — bootout first (idempotent).
        launchctl bootout gui/"$(id -u)" "$f" 2>/dev/null || true
        if launchctl bootstrap gui/"$(id -u)" "$f"; then
          ok "$(basename "$f") bootstrapped"
        else
          err "$(basename "$f") failed to bootstrap — check Console.app for the launchd log"
          SETUP_FAILED=1
          exit 1
        fi
      done
      ;;
    Linux)
      systemctl --user daemon-reload
      systemctl --user enable --now minsky-supervisor.target
      if systemctl --user is-active minsky-supervisor.target >/dev/null 2>&1; then
        ok "minsky-supervisor.target is active"
      else
        err "minsky-supervisor.target failed to activate — see: journalctl --user -u minsky-supervisor.target"
        SETUP_FAILED=1
        exit 1
      fi
      ;;
  esac

  # Report next steps.
  echo
  bold "Minsky is now dogfooding itself."
  echo
  dim "  Web UI:       pnpm dogfood:ui   →   open http://localhost:8181/"
  dim "  Stream logs:  tail -F $STATE_DIR/tick-loop.out.log $STATE_DIR/tick-loop.err.log"
  case "$os" in
    Darwin)
      dim "  Pause:        launchctl bootout gui/\$(id -u) ~/Library/LaunchAgents/com.minsky.tick-loop.plist"
      ;;
    Linux)
      dim "  Pause:        systemctl --user stop minsky-supervisor.target"
      ;;
  esac
  dim "  Status:       launchctl list | grep -i minsky    (macOS)  /  systemctl --user status minsky-supervisor.target  (Linux)"
  dim "  Re-run:       ./setup.sh --dogfood (idempotent; re-renders templates)"
  echo
  ok "GREEN — supervisor loaded; tick-loop will pick the next P0 task on its next cadence"
  exit 0
fi

# --- mode: install (default; reached after --reset too) ---
bold "Minsky setup"
echo

# step: prereqs
CURRENT_STEP="prereqs"
if ! ledger_has "$CURRENT_STEP"; then
  bold "Checking prerequisites…"
  command -v git  >/dev/null 2>&1 || { err "git not found";  SETUP_FAILED=1; exit 1; }
  command -v node >/dev/null 2>&1 || { err "node not found"; SETUP_FAILED=1; exit 1; }
  # Slice 1 of `minsky-fresh-clone-health-checks` — Node major version
  # gate. Fatal if too old (engines `>=20`); pnpm install would later
  # emit `ERR_PNPM_UNSUPPORTED_PLATFORM` with no clear pointer at
  # node version, so catch up-front.
  NODE_MAJOR=$(check_node_major || true)
  if [ -z "$NODE_MAJOR" ]; then
    err "could not parse \`node --version\` — got non-standard output (a version manager misconfiguration?)"
    SETUP_FAILED=1
    exit 1
  fi
  if [ "$NODE_MAJOR" -lt "$MINSKY_NODE_MIN_MAJOR" ]; then
    err "node ${NODE_MAJOR}.x.x is below the >=${MINSKY_NODE_MIN_MAJOR} engine requirement (see package.json engines.node)"
    err "  upgrade with: nvm install ${MINSKY_NODE_MIN_MAJOR} && nvm use ${MINSKY_NODE_MIN_MAJOR}, or brew install node@${MINSKY_NODE_MIN_MAJOR}"
    SETUP_FAILED=1
    exit 1
  fi
  command -v npx  >/dev/null 2>&1 || { err "npx not found";  SETUP_FAILED=1; exit 1; }
  # Slice 1 of `minsky-fresh-clone-health-checks` — pnpm is the install
  # command. Fatal if missing — `pnpm install` is in every documented
  # path (README, setup.sh suggestions, prepare hook, etc.).
  if ! command -v pnpm >/dev/null 2>&1; then
    err "pnpm not found — install via:"
    err "    corepack enable          (preferred, Node ≥16.13)"
    err "    brew install pnpm        (macOS)"
    err "    npm i -g pnpm            (cross-platform fallback)"
    SETUP_FAILED=1
    exit 1
  fi
  command -v claude >/dev/null 2>&1 \
    || warn "claude CLI not found — install: https://docs.claude.com/en/docs/claude-code/overview"
  command -v jq >/dev/null 2>&1 \
    || warn "jq not found — install for setup ledger to work (brew install jq / apt install jq)"
  command -v curl >/dev/null 2>&1 \
    || warn "curl not found — push notifications disabled (NtfyNotifier shells out to curl by default)"
  command -v ntfy >/dev/null 2>&1 \
    || warn "ntfy CLI not found — pushes fall back to curl (graceful-degrade per @minsky/notifier)"
  ok "prerequisites OK"
  ledger_done "$CURRENT_STEP"
else
  ok "prerequisites (cached)"
fi
echo

# step: git
CURRENT_STEP="git-init"
if ! ledger_has "$CURRENT_STEP"; then
  if [ ! -d .git ]; then
    git init -q
    ok "git initialised"
  else
    ok "git already initialised"
  fi
  ledger_done "$CURRENT_STEP"
else
  ok "git (cached)"
fi
echo

# step: tasks-md tooling — install global binaries pinned to ^0.7.0
# NOTE: `tasks install` (the CLI's auto-install of /next-task) is broken in 0.7.0
# (regression tracked at tasksmd/tasks.md PR #77). Skipped here; the SKILL.md
# files at .claude/skills/{next-task,lint-tasks}/ are committed in the repo.
CURRENT_STEP="tasks-md-tooling"
if ! ledger_has "$CURRENT_STEP"; then
  bold "Installing tasks.md tooling (pinned ^0.7.0)…"
  if command -v tasks >/dev/null 2>&1 \
       && command -v tasks-mcp >/dev/null 2>&1 \
       && command -v tasks-lint >/dev/null 2>&1; then
    ok "tasks / tasks-lint / tasks-mcp already on PATH"
  else
    if npm i -g '@tasks-md/cli@^0.7.0' '@tasks-md/lint@^0.7.0' 'tasks-mcp@^0.7.0' 2>>"$LOG_FILE"; then
      ok "tasks-md tooling installed"
    else
      warn "tasks-md tooling install failed; see $LOG_FILE — try manually: npm i -g @tasks-md/cli@^0.7.0 @tasks-md/lint@^0.7.0 tasks-mcp@^0.7.0"
    fi
  fi
  ledger_done "$CURRENT_STEP"
else
  ok "tasks-md tooling (cached)"
fi
echo

# --- final report ---
echo
bold "Summary"
TOPIC="<unset>"
if [ "$have_jq" -eq 1 ]; then
  TOPIC=$(jq -r '.ntfy.topic // "<unset>"' "$STATE_FILE" 2>/dev/null || echo "<unset>")
fi
dim "  ntfy topic       : $TOPIC"
dim "  state file       : $STATE_FILE"
dim "  log file         : $LOG_FILE  (created lazily on tooling-install failures)"
dim "  re-run anytime   : ./setup.sh"
dim "  rebuild from zero: ./setup.sh --reset"
dim "  self-tests only  : ./setup.sh --doctor"
echo
ok "GREEN — minsky setup complete (v0)"
echo
dim "Future P1+ adapter PRs (observability-adapter-v0, supervisor-setup, budget-guard-v0, etc.)"
dim "wire their selfTest() into the --doctor aggregation per the contract documented at"
dim "novel/adapters/types/src/index.ts. Until then, --doctor only checks prerequisites."

# Next-step suggestions (printed after the GREEN banner so the user sees them last).
echo
bold "Next steps inside Claude Code from this directory:"
cat <<'EOF'

  1. /plugin marketplace add https://github.com/Yeachan-Heo/oh-my-claudecode
     /plugin install oh-my-claudecode
     /omc-setup

  2. /plugin install ralph-wiggum

  3. /next-task   (picks the highest-priority unblocked task from TASKS.md)

EOF
